### PR TITLE
Drop TB localization

### LINKED ISSUE #1757: Decommission TB localization
Hi,

Now that the TB instance has been decommissioned, I need to drop the TB-only strings from Pontoon while keeping the other strings.

I’m not sure whether there’s work planned to drop the TB templates from the repository, but I think the easiest way to do this now is to add an exclusion rule to the `makemessages` command in tasks.py.

@mtdenton, would you be able to assign a reviewer for this short PR please?

### PR DESCRIPTION
**Pull request by TheoChevalier**
Closes #1757

This PR excludes custom TB strings from .po files

### CODE REVIEW

**Comment by mtdenton** [comment]
@danielfmiranda could you take a look here when you get a chance? More info in #1757

**Review by danielfmiranda — APPROVED** [review]
Looks good to me! Thanks @TheoChevalier 👍 approved!

**Comment by TheoChevalier** [comment]
Thanks @danielfmiranda ! It seems I can’t merge PRs on this repo, though

**Comment by mtdenton** [comment]
@danielfmiranda could you get this merged during this sprint and make sure everything looks good please? Thanks in advance!

**Comment by danielfmiranda** [comment]
Hi @mtdenton! 

Just merged the PR and deployed to staging. Everything is looking good to me!

**Pull request merged**
