### PR TITLE
remove all ref to the charity image

### LINKED ISSUE #1685: Remove charity navigator logo
**Background**
As a MoFo staffmember, I want to avoid confusing our financial contributors as to our status as a charity. I'd like to remove the "Charity Navigator" logo from our donate.mozilla.org page.

**Acceptance criteria**
- [ ] Charity navigator logo is no longer appearing on donate.mozilla.org

### PR DESCRIPTION
**Pull request by SamirPS**
Closes #1685 
Related PRs/issues #

## Checklist

_Remove unnecessary checks_
I remove all the reference to the image in all file 

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] [Are my changes backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/master/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the documentation?

### CODE REVIEW

**Comment by SamirPS** [comment]
@Pomax

**Comment by SamirPS** [comment]
@Pomax @jzinner

**Comment by Pomax** [comment]
Please do not ping random people. I no longer work for Mozilla, for example. If you want to work on an issue, ask in the issue (which you did) and then when people go "sure!" then by all means do. If they don't, and you just file a PR, then folks will get to your issue and PR when they get to it based on triaging, and it might be a few days or a few months, depending on which of the various projects are currently getting attention from the (small) Mozilla Foundation dev team.

**Comment by SamirPS** [comment]
Ok I understand sorry to ping you

**Comment by Pomax** [comment]
@tbrlpld this keeps showing up in my PR mentions, can this be closed? =)

**Comment by tbrlpld** [comment]
@Pomax I am not familiar with this at all.

**Pull request closed without merging**
